__all__ = [
    "ResponsibleUserNotFoundException",
]


class ResponsibleUserNotFoundException(Exception):
    pass
